"""empty message

Revision ID: 4c7370cdc8a6
Revises:
Create Date: 2026-07-13 15:01:49.433942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c7370cdc8a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulletin",
        sa.Column("exchange_product_id", sa.Integer(), nullable=False),
        sa.Column("exchange_product_name", sa.String(), nullable=False),
        sa.Column("oil_id", sa.String(), nullable=False),
        sa.Column("delivery_basis_id", sa.String(), nullable=False),
        sa.Column("delivery_basis_name", sa.String(), nullable=False),
        sa.Column("delivery_type_id", sa.String(), nullable=False),
        sa.Column("volume", sa.Numeric(), nullable=False),
        sa.Column("total", sa.Numeric(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("date >= '2023-01-01'", name="date_from_2023"),
        sa.CheckConstraint("count > 0", name="count_above_zero"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange_product_id", "date", name="exchange_product_id_date_unique"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bulletin")
    # ### end Alembic commands ###
